### ISSUE TITLE
Renvoyer toutes les structures du CODE_INSEE indiqué quelque soit la distance indiquée dans l'API

### ISSUE THREAD

**Issue by guillett** [betagouv/itou#1537]
Je m'attends à ce que `https://emplois.inclusion.beta.gouv.fr/api/v1/siaes/?code_insee=75056&distance_max_km=1&page_size=100` donne toutes les SIAE de Paris et les SIAE qui sont à moins de 1km de Paris.

J'obtiens une sous partie des SIAE de Paris, qui sont, j'imagine à moins de 1km d'un point (un peu arbitraire) de la zone géographique couverte par Paris.

```bash
curl https://emplois.inclusion.beta.gouv.fr/api/v1/siaes/\?code_insee\=75056\&distance_max_km\=1\&page_size\=1000 > siae_emploi_paris_petit.json

curl https://emplois.inclusion.beta.gouv.fr/api/v1/siaes/\?code_insee\=75056\&distance_max_km\=20\&page_size\=1000 > siae_emploi_paris_large.json

node <<EOF
const petit = require('./siae_emploi_paris_petit.json')
console.log('sous partie', petit.results.length)

const large = require('./siae_emploi_paris_large.json')
console.log('en tout', large.results.filter(i => i.departement == "75").length)
EOF
```

dont le résultats, aujourd'hui et sur ma machine est

```
sous partie 8
en tout 137
```

Cela étant dit, je ne m'attends pas un calcul complexe de la distance des SIAE à la surface qui correspond à Paris mais à une gestion plus fine pour les données dans une commune en particulier.

**Comment by ikarius** [comment]
Effectivement le centre des communes est fourni par `geo.api.gouv.fr` de façon un peu arbitraire, ce qui peut donner des résultats approximatifs lorsque l'on approche de la délimitation de la commune choisie.

La solution rapide est effectivement de prendre de toute façon en compte toutes les SIAEs qui ont le même code commune INSEE que la sélection (ce qui n'est pas fait actuellement).

Une solution plus précise serait de prendre en compte la distance non à partir d'un point arbitraire mais à partir du tracé des contours de la commune.
Cette solution n'est pas disponible actuellement par des API ouvertes à ma connaissance.
Cela peut toutefois être facilement réalisé si nous obtenons des fichiers contours (shp, geojson ou autre) des codes communes INSEE.
Avec la contrainte d'une MaJ nécessaire de ces fichiers chaque année.
Ces fichiers sont disponibles par des sources autre que l'INSEE (ign il me semble).

Nous allons discuter de la priorisation de ce point.

Merci du retour !

**Comment by guillett** [comment]
L'API Géo peut donner les contours (https://geo.api.gouv.fr/decoupage-administratif/communes) mais c'est vraiment plus complexes et je pense que ce niveau de précision ne sera pas utile à grand monde.

En tous cas, merci du retour.
