### ISSUE TITLE
refused_prescriber_organization_email_body.txt

### ISSUE THREAD

**Issue by NathHense** [betagouv/itou#287]
https://github.com/betagouv/itou/blob/dedd9a6201e8101ebe58a9db6a86e0b0f02b7a9e/itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt#L6

 {% trans "Nous sommes désolés, nous n'avons pas pu vérifier l'habilitation de votre organisation. Nous vous recontacterons au plus vite afin d'obtenir les renseignements qui nous manquent. Si toutefois notre tardons à revenir vers vous, n'hésitez pas à relancer notre équipe Support à l'adresse "%}{{ itou_email_contact }}{%

**Comment by ikarius** [comment]
"Si toutefois notre tardons " => "Si toutefois nous tardons" ?
